spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/travely
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
#    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    include:
      - "auth"
    active: default
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS=false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace