auth:
  kakaoOauth2ClinetId: 7e2da5ad6fb5d14c02874cc0880ae024
  frontendRedirectUrl: http://localhost:3000/
  jwtSecretKey: "test"
  tokenValidTime: 10800000

spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:travely}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  # swagger setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  # s3 file upload
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
  profiles:
    include:
      - "auth"
#      - "aws"
      - "domain"
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS=false
  mail:
    host: smtp.gmail.com
    port: 587
    username: hooo0503@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY_ID:test}
      secretKey: ${AWS_S3_SECRET_ACCESS_KEY:test}
    s3:
      bucket: ${AWS_S3_BUCKET:test}
    region:
      static: ap-northeast-2
    stack:
      auto: false
